### ISSUE TITLE
Short output

### ISSUE THREAD

**Issue by daniel-shimon** [anki-code/xontrib-hist-format#1]
This is really cool!

It seems that I can't get output without the links to the xontrib and without both `commands` and `output` sections..
Could you maybe add a flag for short output/make the default short?

When I run `echo hi` and then `hist-md -c1`:

### Current output

[History](https://github.com/anki-code/xontrib-hist-format) output:

```python
echo hi
#hi

```

[History](https://github.com/anki-code/xontrib-hist-format) commands:

```python
echo hi
```

### What I really want

```python
echo hi
#hi

```

**Comment by anki-code** [comment]
Hey @daniel-shimon ! Please update the xontrib:
```
pip install -U xontrib-hist-format
#0.0.5
```

The link removed from the header. The commands list removed in the default output.

About mention - #2
